<?php
/**
 * View Name: block_listing
 * Path: view/admin/block_listing
 * @param array $data arguments passed from controller or route
 */
?>
{{ title        = "Blocks" }}
{{ body_class   = "view-block_listing" }}

{{ content }}
<section>
  <div class="container">
    <h1 class="heading">Blocks</h1>

    <div class="listing-s1">
      <div class="listing-s1__top-bar">
        <div class="align-left">
          <span>Total Blocks: <strong><?=count($blocks)?></strong></span>
        </div>
      </div>

      <table>
        <tr>
          <th>Title</th>
          <th>Slug</th>
        </tr>
        <?php foreach ($blocks as $type => $block) : ?>
          <tr>
            <td class="link-wrap">
              <a href="<?=ADMIN_PATH?>/blocks/<?=$type?>">
                <span class="listing-s1__title"><?=$block['label']?></span>
                <?php if (isset($block['note']) && $block['note'] !== '') :?>
                  <span class="note light-text"><?=$block['note']?></span>
                <?php endif; ?>
              </a>
            </td>
            <td><span class="slug"><?=$block['name']?></span></td>
          </tr>
        <?php endforeach; ?>
      </table>
    </div>
  </div>
</section>
{{ content-end }}