<?php
/**
 * View Name: create_taxonomy
 * Path: view/admin/create_taxonomy
 * @param array $data arguments passed from controller or route
 */

$form_data = has_flash('form_data') ? get_flash('form_data') : [];
$taxonomy_values = isset($edit_data) ? $edit_data : [];
$action = '/admin/taxonomy/create';
$create_class = 'create';
$button_label = 'Create';
$title_label = 'Create';

// Update taxonomy
if (!empty($taxonomy_values)) {
  $action = '/admin/taxonomy/update';
  $form_data = empty($form_data) ? $taxonomy_values : $form_data;
  $create_class = 'edit';
  $button_label = 'Save';
  $title_label = 'Edit';
}

?>
{{ title        = "Create Taxonomy" }}
{{ body_class   = "view-create_post" }}

{{ content }}
  <section>
    <div class="container">
      <div class="heading breadcrumb">
        <span><a href="/admin/taxonomy">Taxonomies</a></span>
      </div>

      <h1 class="heading">
        <span><?=$title_label?> Taxonomy</span>
      </h1>

      <div class="taxonomy-edit-view">
        <div class="ozz-widget">
            <?php _create_form([
              'action' => $action,
              'method' => 'post',
              'class' => 'ozz-fm',
              'field_options' => [
                'wrapper' => '<div class="ozz-fm__field">##</div>'
              ],
              'fields' => [
                [
                  'name' => 'name',
                  'type' => 'text',
                  'label' => 'Name',
                  'validate' => 'req'
                ],
                [
                  'name' => 'slug',
                  'type' => 'text',
                  'label' => 'Slug',
                  'validate' => 'req'
                ],
                [
                  'name' => 'singular_name',
                  'type' => 'text',
                  'label' => 'Singular Name',
                ],
                [
                  'name' => 'meta_keywords',
                  'type' => 'text',
                  'label' => 'Meta Keywords',
                ],
                [
                  'name' => 'meta_description',
                  'type' => 'textarea',
                  'label' => 'Meta Description',
                ],
                [
                  'name' => !empty($taxonomy_values) ? 'taxonomy_id' : '',
                  'type' => 'hidden',
                  'value' => $context['url_parts'][4] ?? ''
                ],
                [
                  'name' => 'crete-btn',
                  'type' => 'button',
                  'value' => $button_label,
                  'class' => 'button small ozz-default-save-button green '.$create_class
                ]
              ]
            ], $form_data); ?>
        </div>
      </div>
    </div>
  </section>
{{ content-end }}