<?php
/**
 * View Name: create_entry
 * Path: view/create_entry
 * @param array $data arguments passed from controller or route
 */
?>
{{ title        = "Create Entry" }}
{{ body_class   = "view-create_entry" }}

{{ content }}
  <section>
    <div class="container">
      <div class="heading breadcrumb">
        <span><a href="<?=ADMIN_PATH?>/forms">Forms</a></span>
        <span><a href="<?=ADMIN_PATH?>/forms/<?=$form_name?>"><?=$form['label']?></a></span>
        <span><a href="<?=ADMIN_PATH?>/forms/<?=$form_name?>/entries">Entries</a></span>
        <span>Create Entry</span>
      </div>

      <h1><?=$form['label']?></h1>
      <?php if (isset($form['note'])) : ?>
        <p class="light-text"><?=$form['note']?></p>
      <?php endif; ?>

      <div class="ozz-widget">
        <?=get_form($form)?>
      </div>
    </div>
  </section>
{{ content-end }}
