<?php
/**
 * View Name: create_post
 * Path: view/admin/create_post
 * @param array $data arguments passed from controller or route
 */
?>
{{ title        = "Create post" }}
{{ body_class   = "view-create_post" }}

{{ content }}
  <section>
    <div class="container">
      <div class="heading breadcrumb">
        <span><a href="<?=ADMIN_PATH?>/posts">Post</a></span>
        <span><a href="<?=ADMIN_PATH?>/posts/<?=$post_type?>"><?=$post_config['label']?></a></span>
      </div>

      <h1 class="heading">
        <span>Create <?=$post_config['singular_label'] ?? ' Entry'?></span>
      </h1>

      <p class="light-text"><?=$post_config['note']?></p>

      <div class="post-edit-view <?=isset($post_config['tabs']) ? 'has-tabs' : ''; ?>">
        <?php _create_form($form['data'], $form['values']); ?>
      </div>
    </div>
  </section>
{{ content-end }}