<?php
/**
 * View Name: dashboard
 * Path: view/admin/dashboard
 * @param array $data arguments passed from controller or route
 */
require __DIR__."/../../storage/system/OzzUpdater.php";
$updater = new OzzUpdater;
?>
{{ title        = "Dashboard" }}
{{ body_class   = "view-dashboard" }}

{{ content }}
  <!-- Fixed Notifications -->
  <?php if ($updater->isUpdateAvailable()) : ?>
    <div class="ozz-notification info ozz-update-notification">
      <span><strong>Update:</strong> A new version of Ozz framework is available: 
        <a href="<?=$updater->getLatestVersion()['support']['source']?>" target="_blank">
          <strong>v<?=ltrim($updater->getLatestVersion()['version'], 'v')?></strong>
        </a>
      </span><br><br>
      <?php _create_form([
        'name' => 'ozzUpdateForm',
        'method' => 'post',
        'action' => ADMIN_PATH.'/ozz-update',
        'fields' => [
          [
            'name' => 'updatebtn',
            'type' => 'submit',
            'value' => 'Update Now',
            'class' => 'button small'
          ]
        ]
      ]) ?>
    </div>
  <?php endif;?>

  <h1>Dashboard</h1>
  <section class="widget-box-wrapper">
    <div class="widget-box blue">
      <div class="cl cl-6">
        <span class="light-text f-14">Post types</span>
        <h3><?=count($post_types)?></h3>
      </div>

      <div class="cl cl-6">
        <span class="light-text f-14">Posts</span>
        <h3><?=$post_count?></h3>
      </div>

      <a href="<?=ADMIN_PATH?>/posts" class="button mini">Posts</a>
    </div>

    <div class="widget-box blue">
      <div>
        <span class="light-text f-14">Blocks</span>
        <h3><?=count($blocks)?></h3>
      </div>
      <a href="<?=ADMIN_PATH?>/blocks" class="button mini">Blocks</a>
    </div>

    <div class="widget-box blue">
      <div class="cl cl-6">
        <span class="light-text f-14">Taxonomies</span>
        <h3><?=count($taxonomies)?></h3>
      </div>

      <div class="cl cl-6">
        <span class="light-text f-14">Terms</span>
        <h3><?=$terms_count?></h3>
      </div>
      <a href="<?=ADMIN_PATH?>/taxonomy" class="button mini">Taxonomies</a>
    </div>

    <div class="widget-box blue">
      <div class="cl cl-6">
        <span class="light-text f-14">Forms</span>
        <h3><?=count($forms)?></h3>
      </div>

      <div class="cl cl-6">
        <span class="light-text f-14">Entries</span>
        <h3><?=$entries_count?></h3>
      </div>
      <a href="<?=ADMIN_PATH?>/forms" class="button mini">Forms</a>
    </div>
  </section><br>

  <section class="recent-entries">
    <h3>Recent Entries</h3>
    <table class="ozz-table">
      <tr>
        <th>ID</th>
        <th>Data</th>
        <th>Form</th>
        <th>Created</th>
        <th></th>
      </tr>
      <?php foreach ($recent_entries as $key => $item) : ?>
        <tr class="<?=in_array($item['id'], $new_entries_ids) ? 'new-entry-label' : ''?>">
          <td><?=$key+1?></td>
          <td><?=substr($item['content'], 0, 100)?>...</td>
          <td><?=$item['name']?></td>
          <td class="light-text f-14"><?=ozz_format_date($item['created'])?></td>
          <td class="align-right">
            <a href="<?=ADMIN_PATH?>/forms/<?=$item['name']?>/entry/<?=$item['id']?>" class="button micro">View</a>
          </td>
        </tr>
      <?php endforeach; ?>
    </table>
    <br>
    <a href="<?=ADMIN_PATH?>/forms" class="button mini">All Entries</a>
  </section>
{{ content-end }}