<?php
/**
 * View Name: edit_entry
 * Path: view/edit_entry
 * @param array $data arguments passed from controller or route
 */
?>
{{ title        = "Edit Entry" }}
{{ body_class   = "view-edit_entry" }}

{{ content }}
  <section>
    <div class="container">
      <div class="heading breadcrumb">
        <span><a href="<?=ADMIN_PATH?>/forms">Forms</a></span>
        <span><a href="<?=ADMIN_PATH?>/forms/<?=$form['name']?>"><?=$form['label']?></a></span>
        <span><a href="<?=ADMIN_PATH?>/forms/<?=$form['name']?>/entries">Entries</a></span>
        <span><a href="<?=ADMIN_PATH?>/forms/checkout/entry/<?=$entry['id']?>">Edit Entry #<?=$entry['id']?></a></span>
      </div>

      <h1><?=$form['label']?></h1>
      <?php if (isset($form['note'])) : ?>
        <p class="light-text"><?=$form['note']?></p>
      <?php endif; ?>

      <div class="ozz-widget">
        <?=get_form($form, $entry['fields'])?>
      </div>
    </div>
  </section>
{{ content-end }}
