<?php
/**
 * View Name: edit_post
 * Path: view/admin/edit_post
 * @param array $data arguments passed from controller or route
 */

$post_info = array_merge($form_data, ['languages' => $languages]);
$page_title = "Edit ".$post_config['label'].' - '.$form_data['title'];

?>
{{ title        = page_title }}
{{ body_class   = "view-edit-post" }}

{{ content }}
  <section>
    <div class="container">
      <div class="heading breadcrumb">
        <span><a href="<?=ADMIN_PATH?>/posts">Post</a></span>
        <span><a href="<?=ADMIN_PATH?>/posts/<?=$post_type?>"><?=$post_config['label']?></a></span>
      </div>

      <h1>
        <span class="label dot <?=$form_data['post_status']?>"></span>
        <span class="j-title-onchange"><?=$form_data['title']?></span>
      </h1>

      <div class="post-edit-view <?=isset($post_config['tabs']) ? 'has-tabs' : ''; ?>">
        <?php
          _create_form($form['data'], $form['values']);
          _component('post-info', $post_info, 'cms');
        ?>
      </div>
    </div>
  </section>
{{ content-end }}