<?php
/**
 * View Name: form
 * Path: view/admin/form
 * @param array $data arguments passed from controller or route
 */

$page_title = esc('Form | '.($form['label'] ?? ($form['name'] ?? 'Form not found')));

?>
{{ title        = page_title }}
{{ body_class   = "view-form" }}

{{ content }}
  <section>
    <div class="container">
      <?php if (!empty($form)) : ?>
        <div class="heading breadcrumb">
          <span><a href="<?=ADMIN_PATH?>/forms">Forms</a></span>
          <span><?=esc($form['label'])?></span>
        </div>

        <h1 class="heading cl cl-6"><?=esc($form['label'])?></h1>
        <div class="cl cl-6 align-right">
          <a href="<?=ADMIN_PATH?>/forms/create/<?=esc($form['name'])?>" class="button green small">Create Entry</a>
          <a href="<?=ADMIN_PATH?>/forms/<?=esc($form['name'])?>/entries" class="button small">Entries</a>
        </div>

        <div class="ozz-widget">
          <h4 class="ozz-widget__heading">Form Info</h4>
          <div class="ozz-widget__item-raw">
            <label>Title: </label><span><?=esc($form['label'])?></span>
          </div>
          <div class="ozz-widget__item-raw">
            <label>Name: </label><span><?=esc($form['name'])?></span>
          </div>
          <div class="ozz-widget__item-raw">
            <label>Action: </label><span><?=esc($form['action'] ?? 'Tracking')?></span>
          </div>
          <div class="ozz-widget__item-raw">
            <label>Note: </label><span><?=esc($form['note'] ?? '')?></span>
          </div>
        </div><br>

        <div class="ozz-widget">
          <h4 class="ozz-widget__heading">Fields</h4>
          <?= json_dump( json_encode($form['fields']) ) ?>
        </div>
      <?php else : ?>
        <h1 class="heading">form</h1>
        <div class="listing-s2__empty">
          <p>Invalid form</p>
        </div>
      <?php endif; ?>
    </div>
  </section>
{{ content-end }}