<?php
/**
 * View Name: media
 * Path: view/admin/media
 * 
 * @param array $data arguments passed from controller or route
 */

$current_dir = '';

?>
{{ title        = "Media" }}
{{ body_class   = "view-media" }}

{{ content }}
  <br>
  <div class="ozz-media-manager">
    <?php if (!empty($media_directory_tree)) : ?>
      <div class="ozz-media-manager__breadcrumb">
        <a href="/admin/media" class="ozz-media-manager__breadcrumb-home"><span></span></a>
        <?php
        foreach ($media_directory_tree as $key => $dir) :
          $separator = $key !== 0 && $key !== count($media_directory_tree) ? '/' : '';
          $current_dir .= $separator.$dir;
        ?>
          <a href="/admin/media?dir=<?=urlencode($current_dir)?>" title="<?=$dir?>">
            <?= char_limit($dir, 15, '..') ?>
          </a> /
        <?php endforeach; ?>
      </div>
    <?php endif; ?>

    <!-- Media Actions -->
    <div class="ozz-media-manager__actions">
      <div class="ozz-media-manager__actions-action popup-trigger create-folder">
        <button class="button mini">+ New Folder</button>
        <div class="hidden-action-form" id="ozz-media-create-new-directory">
          <h2>Create New Directory</h2>
          <?php _create_form([
          'method' => 'post',
          'action' => '/admin/media/action?q=create_folder',
          'class' => 'ozz-fm',
          'fields' => [
            [
              'name' => 'ozz_media_current_directory',
              'type' => 'hidden',
              'value' => $current_dir
            ],[
              'name' => 'ozz_media_folder_name',
              'type' => 'text',
              'label' => 'Directory Name',
              'note' => $current_dir.'/',
              'data-ozz-validate' => 'test',
            ],[
              'name' => 'ozz_media_create_folder_submit',
              'type' => 'submit',
              'value' => 'Create',
              'class' => 'button small'
            ]
          ]
        ]); ?>
        </div>
      </div>
      <div class="ozz-media-manager__actions-action popup-trigger create-file">
        <button class="button mini">+ New File</button>
        <div class="hidden-action-form" id="ozz-media-create-new-file">
          <h2>Create New File</h2>
          <?php _create_form([
          'method' => 'post',
          'action' => '/admin/media/action?q=create_file',
          'class' => 'ozz-fm',
          'fields' => [
            [
              'name' => 'ozz_media_current_directory',
              'type' => 'hidden',
              'value' => $current_dir
            ],[
              'name' => 'ozz_media_file_name',
              'type' => 'text',
              'label' => 'File Name',
              'note' => $current_dir.'/'
            ],[
              'name' => 'ozz_media_create_file_submit',
              'type' => 'submit',
              'value' => 'Create',
              'class' => 'button small'
            ]
          ]
        ]); ?>
        </div>
      </div>
      <div class="ozz-media-manager__actions-action popup-trigger upload">
        <button class="button mini">Upload</button>
        <div class="hidden-action-form" id="ozz-media-upload-file">
          <h2>Upload File</h2>
          <?php _create_form([
            'method' => 'post',
            'enctype' => 'multipart/form-data',
            'action' => '/admin/media/action?q=upload_file',
            'class' => 'ozz-fm',
            'fields' => [
              [
                'name' => 'ozz_media_current_directory',
                'type' => 'hidden',
                'value' => $current_dir
              ],[
                'name' => 'ozz_media_upload_file[]',
                'type' => 'file',
                'class' => 'ozz-upload-button',
                'multiple' => 'multiple'
              ],[
                'name' => 'ozz_media_upload_file_submit',
                'type' => 'submit',
                'class' => 'button small',
                'value' => 'Upload'
              ]
            ]
          ]); ?>
        </div>
      </div>
      <?php if ($current_dir !== '') : ?>
      <div class="ozz-media-manager__actions-action popup-trigger delete-dir">
        <?php _create_form([
          'method' => 'post',
          'action' => '/admin/media/action?q=delete_dir',
          'class' => 'ozz-fm',
          'fields' => [
            [
              'name' => 'ozz_media_current_directory',
              'type' => 'hidden',
              'value' => $current_dir
            ],[
              'name' => 'ozz_media_create_file_submit',
              'type' => 'submit',
              'value' => 'Delete Directory',
              'class' => 'button mini danger'
            ]
          ]
        ]); ?>
      </div>
      <?php endif; ?>

      <div class="ozz-media-manager__actions-action search">
        <?php _create_form([
          'method' => 'post',
          'class' => 'ozz-fm',
          'fields' => [
            [
              'name' => 'ozz_media_search_keyword',
              'type' => 'search',
              'placeholder' => 'Search',
            ],[
              'name' => 'ozz_media_search',
              'value' => 'Search',
              'type' => 'submit',
              'class' => 'button mini'
            ]
          ]
        ]); ?>
      </div>
    </div>

    <div class="ozz-media-manager__media-wrapper">
      <div class="ozz-media-manager__media">
        <?php if(is_array($media_items['data']) && count($media_items['data']) > 0) : ?>
          <div class="ozz-media-manager__items">
            <?php
              foreach ($media_items['data'] as $key => $item) :
                if ($item['type'] == 'file') :
              ?>
                <div class="ozz-media-manager__item media-file" data-fileInfo='<?=json_encode($item, true)?>'>
                  <div class="ozz-media-manager__item-file">
                    <div class="ozz-media-manager__item-thumbnail">
                      <?php if($item['format'] == 'image') :?>
                        <img src="/<?=$item['url'] ?>" alt="<?=$item['name']?>" width="150px" />
                      <?php elseif($item['format'] == 'svg') :?>
                        <object type="image/svg+xml" data="/<?=$item['url'] ?>">
                          <img src="/<?=$item['url'] ?>" alt="<?=$item['name'] ?>" />
                        </object>
                      <?php else : ?>
                        <div class="icon <?=$item['format']?>">
                          <strong><?=$item['format']?></strong>
                          <span class="name"><?=$item['name']?></span>
                        </div>
                      <?php endif; ?>
                    </div>
                  </div>
                </div>
              <?php else: ?>
                <div class="ozz-media-manager__item media-folder">
                  <a href="?dir=<?=urlencode($item['url'])?>"
                    class="ozz-media-manager__item-folder" title="<?=$item['name']?>">
                    <span class="ozz-media-manager__item-name"><?= char_limit($item['name'], 15, '..') ?></span>
                  </a>
                </div>
              <?php endif; ?>
              <?php endforeach; ?>
          </div>

          <!-- Pagination -->
          <div class="ozz-media-manager__pagination ozz-pagination">
            <span><?= pagination_dom($media_items['number_of_pages'], $media_items['current_page']); ?></span>
            <span class="light-text"><strong><?= count($media_items['data']); ?></strong> Items</span>
          </div>

        <?php elseif(empty($media_items['data'])) : ?>
          <div class="listing-s2__empty">
            <p>Empty</p>
          </div>
        <?php endif; ?>
      </div>

      <!-- File viewer -->
      <div class="ozz-media-manager__viewer" id="ozz_media_viewer"></div>
    </div>
  </div>
{{ content-end }}