<?php
/**
 * View Name: post_listing
 * Path: view/admin/post_listing
 * 
 * @param array $data arguments passed from controller or route
 */
?>
{{ title        = "Posts" }}
{{ body_class   = "post post__listing" }}

{{ content }}
<h1>Posts: <?=$post_type_label?></h1>
<div class="listing-s2">
  <div class="listing-s2__header">
    <div class="listing-s2__filter" 
      data-active-tab="<?=isset($context['query']['status']) ? $context['query']['status'] : '';?>">
      <a class="button mini light tab-button all" href="/admin/posts/<?=$post_type?>">
        <span>All <strong><?=$posts['count']['all']?></strong></span>
      </a>
      <a class="button mini light tab-button published" href="/admin/posts/<?=$post_type?>?status=published">
        <span>Published <strong><?=$posts['count']['published']?></strong></span>
      </a>
      <a class="button mini light tab-button draft" href="/admin/posts/<?=$post_type?>?status=draft">
        <span>Draft <strong><?=$posts['count']['draft']?></strong></span>
      </a>
      <a class="button mini light tab-button trash" href="/admin/posts/<?=$post_type?>?status=trash">
        <span>Trash <strong><?=$posts['count']['trash']?></strong></span>
      </a>
    </div>
    <div class="align-right">
      <a href="/admin/posts/create/<?=$post_type?>" class="button small green">Create New</a>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Status</th>
        <th>Created</th>
        <th>Modified</th>
        <th>Author</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <?php foreach ($posts['listing'] as $key => $value) : ?>
        <tr>
          <td>
            <span class="title"><?=$value['title']?></span>
            <a href="/admin/posts/edit/<?=$value['post_type']?>/<?=$value['post_id']?>" class="anchor-wrapper"></a>
          </td>
          <td width="120px">
            <span class="label <?=$value['post_status']?>">
              <?=ucfirst($value['post_status'])?>
            </span>
          </td>
          <td width="120px"><span class="light-text"><?=date('M d, Y', $value['created_at'])?></span></td>
          <td width="120px"><span class="light-text"><?=date('M d, Y', $value['modified_at'])?></span></td>
          <td width="180px" class="f-14"><?=$value['first_name'].' '.$value['last_name']?></td>
          <td class="tr-action" width="180px">
            <div class="show-on-hover">
              <a href="/admin/posts/edit/<?=$value['post_type']?>/<?=$value['post_id']?>" title="Edit">
                <span class="icon-button edit"></span>
              </a>

              <?php if($value['post_status'] !== 'trash') : ?>
                <form action="/admin/post/duplicate" method="post" class="action-form duplicate-form">
                  <?=CSRF_FIELD?>
                  <input type="hidden" name="post_id" value="<?=$value['id']?>">
                  <button type="submit" title="Duplicate">
                    <span class="icon-button duplicate"></span>
                  </button>
                </form>
              <?php endif; ?>

              <?php if($value['post_status'] == 'published') : ?>
                <form action="/admin/post/change-status" method="post" class="action-form draft-form">
                  <?=CSRF_FIELD?>
                  <input type="hidden" name="post_id" value="<?=$value['id']?>">
                  <input type="hidden" name="status" value="draft">
                  <button type="submit" title="Draft">
                    <span class="icon-button draft"></span>
                  </button>
                </form>
              <?php else : ?>
                <form action="/admin/post/change-status" method="post" class="action-form publish-form">
                  <?=CSRF_FIELD?>
                  <input type="hidden" name="post_id" value="<?=$value['id']?>">
                  <input type="hidden" name="status" value="published">
                  <button type="submit" title="Publish">
                    <span class="icon-button publish"></span>
                  </button>
                </form>
              <?php endif; ?>

              <form action="/admin/posts/delete" method="post" class="action-form post-delete-form">
                <?=CSRF_FIELD?>
                <input type="hidden" name="post_id" value="<?=$value['id']?>">
                <input type="hidden" name="delete_type" value="<?=$value['post_status'] == 'trash' ? 'delete' : 'trash'; ?>">
                <button type="submit" title="Delete">
                  <span class="icon-button delete"></span>
                </button>
              </form>
            </div>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

  <?php if(count($posts['listing']) == 0) : ?>
    <div class="listing-s2__empty">
      <p>No results found</p>
    </div>
  <?php endif; ?>
</div>
{{ content-end }}