<?php
/**
 * View Name: taxonomy
 * Path: view/admin/taxonomy
 * @param array $data arguments passed from controller or route
 */

$page_title = 'Taxonomy | '.($taxonomy['name'] ?? 'Taxonomy not found');
?>
{{ title        = page_title }}
{{ body_class   = "view-taxonomy" }}

{{ content }}
  <section>
    <?php if (!empty($taxonomy)) : ?>
      <div class="heading breadcrumb">
        <span><a href="/admin/taxonomy">Taxonomy</a></span>
        <span><a href=""><?=$taxonomy['name']?></a></span>
      </div>

      <h1 class="heading"><?=$taxonomy['name']?></h1>

      <div class="cl cl-6">
        <div class="ozz-widget">
          <h4 class="ozz-widget__heading">Taxonomy Info</h4>
          <div class="ozz-widget__item-raw">
            <label>Name: </label><span><?=$taxonomy['name']?></span>
          </div>
          <div class="ozz-widget__item-raw">
            <label>Slug: </label><span><?=$taxonomy['slug']?></span>
          </div>

          <?php if (isset($taxonomy['terms'])) : ?>
            <div class="ozz-widget__item-raw">
              <label>Terms: </label><br><br>
              <?php foreach ($taxonomy['terms'] as $term) : ?>
                <span class="button mini light"><?=$term['name']?></span>
              <?php endforeach; ?>
            </div>
          <?php endif; ?>

          <br>
          <?php _create_form([
            'action' => '/admin/taxonomy/create-term',
            'method' => 'post',
            'class' => 'ozz-fm',
            'field_options' => [
              'wrapper' => '<div class="ozz-fm__field">##</div>',
            ],
            'fields' => [
              [
                'name' => 'name',
                'type' => 'text',
                'label' => 'Term',
                'wrapper_class' => 'cl cl-6',
              ],
              [
                'name' => 'slug',
                'type' => 'text',
                'label' => 'Slug',
                'wrapper_class' => 'cl cl-6',
              ],
              [
                'name' => 'taxonomy_id',
                'type' => 'hidden',
                'value' => $taxonomy['id'],
                'wrapper' => false,
              ],
              [
                'name' => 'submit',
                'type' => 'submit',
                'value' => '+ Add',
                'class' => 'button mini green',
              ]
            ]
          ])?>

        </div>
      </div>
    <?php else : ?>
      <h1 class="heading">Taxonomy</h1>
      <div class="listing-s2__empty">
        <p>Invalid taxonomy</p>
      </div>
    <?php endif; ?>
  </section>
{{ content-end }}