<?php
/**
 * View Name: dashboard
 * Path: view/auth/dashboard
 * 
 * @param array $data arguments passed from controller
 * 
 */
?>
{{ title     = "Dashboard" }}
{{ bodyClass = "user-dashboard" }}

{{ content }}
  <section>
    <div class="container">
      <h1>Hi! <?=$data['last_name']?></h1>
      <img src="<?=get_gravatar($data['email'], 80);?>" alt="Avatar">
    </div>
  </section>
{{ content-end }}