<?php
/**
 * View Name: forgot-password
 * Path: view/auth/forgot-password
 * 
 * @param array $data arguments passed from controller
 * 
 */
?>
{{ title        = "Forgot Password | <?=APP_NAME?>" }}
{{ bodyClass    = "auth" }}

{{ content }}
  <section class="component auth-comp forgot-password center">
    <div class="container">
      <h1 class="component__heading-1">Forgot Password</h1>
      <p>Enter the email. We'll send you a link to reset your password</p>
      <form action="<?=BASE_URL?>forgot-password" method="post" class="form">

        <?=CSRF_FIELD?>

        <div class="form-item">
          <input type="email" name="email" placeholder="Email Address">
        </div>

        <div class="form-error">
          <?php show_errors('<p>##</p>'); ?>
        </div>

        <input type="submit" value="Submit">
      </form>
    </div>

  </section>

  <div class="off-bottom-link">
    <a href="<?=BASE_URL?>/login" class="link">Back to Login</a>
  </div>
{{ content-end }}
