<?php
/**
 * View Name: reset-password
 * Path: view/auth/reset-password
 * 
 * @param array $data arguments passed from controller
 * 
 */
?>
{{ title        = "Reset Password | <?=APP_NAME?>" }}
{{ bodyClass    = "auth" }}

{{ content }}
  <section class="component auth-comp reset-password center">
    <div class="container">
      <h1 class="component__heading-1">Reset Password</h1>
      <form action="<?=BASE_URL?>reset-password" method="post" class="form">

        <?=CSRF_FIELD?>

        <div class="form-item">
          <input type="password" name="password" placeholder="New Password" autocomplete="new-password">
        </div>

        <div class="form-item">
          <input type="password" name="confirm_password" placeholder="Confirm New Password" autocomplete="new-password">
        </div>

        <div class="form-error">
          <?php show_errors('<p>##</p>'); ?>
        </div>

        <input type="submit" value="Reset Password">
      </form>
    </div>
  </section>
{{ content-end }}
