<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="x-apple-disable-message-reformatting">
  <title>Email Verification</title>
  <style>
    body { 
      background-color: #eeeff8;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
    }
    .container {
      padding: 40px;
      background: #ffffff;
      max-width: 450px;
      margin: 0 auto;
    }
    button {
      background: #666EE8;
      padding: 12px 20px;
      border-radius: 5px;
      border: none;
      cursor: pointer;
    }
    button:hover {
      background: #5860cf;
    }
    a {
      color: #ffffff;
      text-decoration: none;
      font-size: 16px;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1 style="color: #333333;font-size: 24px;margin: 0 0 30px;">Verify You Email Address</h1>
    <p style="margin-bottom: 30px;color: #666666;line-height:22px;">Hi <strong>{{ name }}</strong>,</p>
    <p style="margin-bottom: 30px;color: #666666;line-height:22px;">You have successfully created a {{ app_name }} account. Please click the link below to verify your email address and complete your registration</p>
    <button>
      <a href="{{ verify_link }}" target="_blank">Verify your email</a>
    </button>
  </div>
</body>
</html>