<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="x-apple-disable-message-reformatting">
  <title>Your password has been changed</title>
  <style>
    body { 
      background-color: #eeeff8;
      font-family: Arial, sans-serif;
      margin: 0;
      padding: 20px;
    }
    .container {
      padding: 40px;
      background: #ffffff;
      max-width: 450px;
      margin: 0 auto;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1 style="color: #333333;font-size: 24px;margin: 0 0 30px;">Did you change your password?</h1>
    <p style="margin-bottom: 30px;color: #666666;line-height:22px;">Hello {{ name }}, Your password has been changed recently. If this was you, you can safely ignore this email.</p>
    <div style="padding: 5px 15px;background: #f7f8ff;">
      {{ info_dom }}
    </div>
  </div>
</body>
</html>