<?php
/**
 * View Name: admin
 * Path: view/auth/admin
 * @param array $data arguments passed from controller
 */
?>

{{ title = "Admin" }}
{{ body_class = "dashboard" }}

{{ content }}
<section class="app-view app-view--admin">
  <div class="app-container auth-card">
    <img
      src="<?=get_gravatar($email, 128);?>"
      alt="Avatar"
      class="profile-avatar"
    >
    <h1 class="profile-name"><?=$first_name.' '.$last_name?></h1>
    <p class="profile-username"><?=$username?></p>
    <p class="profile-email"><?=$email?></p>
  </div>
</section>
{{ content-end }}
