<?php
/**
 * View Name: forgot-password
 * Path: view/auth/forgot-password
 * @param array $data arguments passed from controller
 */

$value = has_flash('form_data') ? (object) get_flash('form_data') : false;
?>

{{ title = "Forgot Password | <?=APP_NAME?>" }}
{{ body_class = "auth" }}

{{ content }}
<section class="auth">
  <div class="auth-card">
    <h1 class="auth-title">Forgot Password</h1>
    <p class="auth-subtitle">Enter your email. We'll send you instructions to reset your password</p>
    <form method="post" action="<?=AUTH_PATHS['forgot_password']?>" class="form">
      <?=CSRF_FIELD?>
      <div class="form-group">
        <input
          type="email"
          name="email"
          class="form-input <?=has_error('email') ? 'is-error' : '' ?>"
          value="<?=$value->email ?? ''?>"
          placeholder="Email Address"
        >
        <?=show_error('email', '<span class="form-error">##</span>')?>
      </div>
      <button class="app-button app-button--primary is-full">Submit</button>
      <?=show_error('success', '<p class="form-message success">##</p>')?>
      <?=show_error('error', '<p class="form-message error">##</p>')?>
    </form>
    <div class="auth-footer">
      <a href="<?=AUTH_PATHS['login']?>">Back to login</a>
    </div>
  </div>
</section>
{{ content-end }}
