<?php
/**
 * View Name: forgot-password
 * Path: view/auth/forgot-password
 * 
 * @param array $data arguments passed from controller
 * 
 */

$value = has_flash('form_data') ? (object) get_flash('form_data') : false;

?>

{{ title        = "Forgot Password | <?=APP_NAME?>" }}
{{ body_class   = "auth" }}

{{ content }}
  <section class="component auth-comp forgot-password center">
    <div class="container">
      <h1 class="component__heading-1">Forgot Password</h1>
      <p>Enter the email. We'll send you a link to reset your password</p>
      <form action="<?=AUTH_PATHS['forgot_password']?>" method="post" class="form">

        <?=CSRF_FIELD?>

        <div class="form-item">
          <input type="email" name="email" placeholder="Email Address" value="<?=$value->email ?? '' ?>" class="<?=has_error('email') ? 'error' : false ?>">
          <?=show_error('email', '<span class="error-label">##</span>')?>
        </div>

        <div class="form-error">
          <?=show_error('success', '<p class="message success">##</p>'); ?>
          <?=show_error('error', '<p class="message danger">##</p>'); ?>
        </div>

        <input type="submit" value="Submit">
      </form>
    </div>

  </section>

  <div class="off-bottom-link">
    <a href="<?=AUTH_PATHS['login']?>" class="link">Back to Login</a>
  </div>
{{ content-end }}