<?php
/**
 * View Name: forgot-password
 * Path: view/auth/forgot-password
 * @param array $data arguments passed from controller
 */

$value = has_flash('form_data') ? (object) get_flash('form_data') : false;
?>

{{ title        = "Forgot Password | <?=APP_NAME?>" }}
{{ body_class   = "auth" }}

{{ content }}
<section class="section auth-comp">
  <div class="container">
    <h1 class="title has-text-centered">Forgot Password</h1>
    <p class="has-text-centered">
      Enter your email. We'll send you a link to reset your password.
    </p>
    <form action="<?=AUTH_PATHS['forgot_password']?>" method="post">
      
      <?=CSRF_FIELD?>
      
      <div class="field my-5">
        <label class="label" for="email">Email Address</label>
        <div class="control">
          <input
            id="email"
            type="email"
            name="email"
            placeholder="Email Address"
            value="<?=$value->email ?? '' ?>"
            class="input <?=has_error('email') ? 'is-danger' : '' ?>">
        </div>
        <?=show_error('email', '<p class="help is-danger">##</p>')?>
      </div>

      <div class="field">
        <div class="control">
          <button type="submit" class="button is-primary is-fullwidth">Submit</button>
        </div>
      </div>

      <?=show_error('success', '<p class="notification is-success">##</p>'); ?>
      <?=show_error('error', '<p class="notification is-danger">##</p>'); ?>
    </form>
  </div>

  <div class="has-text-centered mt-4">
    <a href="<?=AUTH_PATHS['login']?>" class="is-text">Back to Login</a>
  </div>
</section>
{{ content-end }}