<?php
/**
 * View Name: login
 * Path: view/login
 * @param array $data arguments passed from controller
 */

$value = has_flash('form_data') ? (object) get_flash('form_data') : false;
$redirect = isset($context['query']['redirect']) ? '?redirect='.$context['query']['redirect'] : '';
?>

{{ title        = "Login | <?=APP_NAME?>" }}
{{ keywords     = "login" }}
{{ description  = "Login" }}
{{ body_class   = "auth" }}

{{ content }}
  <section class="section auth-comp">
    <div class="container">
      <h1 class="title has-text-centered">Login</h1>
      <form action="<?=AUTH_PATHS['login'].$redirect?>" method="post" class="form">

        <?=CSRF_FIELD?>

        <div class="field my-5">
          <div class="control">
            <input type="email" name="email" placeholder="Email" value="<?=$value->email ?? '' ?>" class="input <?=has_error('email') ? 'is-danger' : ''?>">
          </div>
          <?=show_error('email', '<span class="help is-danger">##</span>')?>
        </div>

        <div class="field my-5">
          <div class="control">
            <input type="password" name="password" placeholder="Password" autocomplete="new-password" value="<?=$value->password ?? '' ?>" class="input <?=has_error('password') ? 'is-danger' : ''?>">
          </div>
          <?=show_error('password', '<span class="help is-danger">##</span>')?>
        </div>

        <div class="field">
          <?=show_error('success', '<p class="message is-success">##</p>'); ?>
          <?=show_error('error', '<p class="message is-danger">##</p>'); ?>
        </div>

        <div class="field">
          <div class="control">
            <input type="submit" value="Login" class="button is-primary is-fullwidth">
          </div>
        </div>
      </form>
    </div>
  </section>

  <div class="has-text-centered">
    <a href="<?=AUTH_PATHS['signup']?>" class="is-text">Create an account</a>
    &nbsp;|&nbsp;
    <a href="<?=AUTH_PATHS['forgot_password']?>" class="is-text">Forgot Password?</a>
  </div>
{{ content-end }}