<?php
/**
 * View Name: reset-password
 * Path: view/auth/reset-password
 * @param array $data arguments passed from controller
 */
?>

{{ title        = "Reset Password | <?=APP_NAME?>" }}
{{ body_class   = "auth" }}

{{ content }}
<?php if ($status === 'valid_token') : ?>
  <section class="section">
    <div class="container">
      <h1 class="title has-text-centered">Reset Your Password</h1>
      <form action="<?= AUTH_PATHS['reset_password'] ?>" method="post">
        <?= CSRF_FIELD ?>
        <input type="hidden" name="token" value="<?= $token ?>">
        <div class="field">
          <label class="label" for="password">New Password</label>
          <div class="control">
            <input
              id="password"
              type="password"
              name="password"
              placeholder="New Password"
              autocomplete="new-password"
              class="input <?=has_error('password') ? 'is-danger' : '' ?>"
            >
          </div>
          <?=show_error('password', '<p class="help is-danger">##</p>')?>
        </div>

        <div class="field">
          <label class="label" for="confirm_password">Confirm New Password</label>
          <div class="control">
            <input
              id="confirm_password"
              type="password"
              name="confirm_password"
              placeholder="Confirm New Password"
              autocomplete="new-password"
              class="input <?=has_error('confirm_password') ? 'is-danger' : '' ?>"
            >
          </div>
          <?=show_error('confirm_password', '<p class="help is-danger">##</p>')?>
        </div>

        <div class="field">
          <?php show_errors('<p class="message is-danger">##</p>'); ?>
        </div>

        <div class="field">
          <div class="control">
            <button type="submit" class="app-button is-primary is-fullwidth">Reset Password</button>
          </div>
        </div>
      </form>
    </div>
  </section>

<?php elseif ($status === 'success') : ?>

  <section class="section has-text-centered auth-comp">
    <h1 class="app-title">Password Changed!</h1>
    <p class="app-subtitle">Your password has been changed successfully.</p>
    <a href="<?= AUTH_PATHS['login'] ?>" class="app-button is-primary">Login</a>
  </section>

<?php elseif ($status === 'expired_token') : ?>

  <section class="section has-text-centered auth-comp">
    <h1 class="app-title">Password Reset Link Expired</h1>
    <p class="app-subtitle">Please request a new one and try again.</p>
    <a href="<?= AUTH_PATHS['forgot_password'] ?>" class="app-button is-warning">Forgot Password</a>
  </section>

<?php elseif ($status === 'invalid_token') : ?>

  <section class="section has-text-centered auth-comp">
    <h1 class="app-title">Invalid Reset Link</h1>
    <p class="app-subtitle">Please request a new one and try again.</p>
    <a href="<?= AUTH_PATHS['forgot_password'] ?>" class="app-button is-warning">Forgot Password</a>
  </section>

<?php else : ?>

  <section class="section has-text-centered auth-comp">
    <h1 class="app-title">Unknown Error</h1>
    <p class="app-subtitle">Something went wrong. Please try again later.</p>
  </section>

<?php endif; ?>
{{ content-end }}