<?php
/**
 * View Name: reset-password
 * Path: view/auth/reset-password
 * 
 * @param array $data arguments passed from controller
 * 
 */
?>

{{ title        = "Reset Password | <?=APP_NAME?>" }}
{{ bodyClass    = "auth" }}

{{ content }}
<?php if($status === 'valid_token') : ?>
  <section class="component auth-comp reset-password center">
    <div class="container">
      <h1 class="component__heading-1">Reset your password</h1>
      <form action="<?= AUTH_RESET_PASSWORD_PATH ?>" method="post" class="form">

        <?=CSRF_FIELD?>

        <input type="hidden" name="token" value="<?=$token?>">

        <div class="form-item">
          <input type="password" name="password" placeholder="New Password" autocomplete="new-password">
        </div>

        <div class="form-item">
          <input type="password" name="confirm_password" placeholder="Confirm New Password" autocomplete="new-password">
        </div>

        <div class="form-error">
          <?php show_errors('<p>##</p>'); ?>
        </div>

        <input type="submit" value="Reset Password">
      </form>
    </div>
  </section>

<?php elseif($status === 'success') : ?>

  <section class="component auth-comp center">
    <h1 class="component__heading-1">Password changed!</h1>
    <p>Your password has been changed successfully.</p>
    <a href="<?=AUTH_LOGIN_PATH?>" class="button">Login</a>
  </section>

<?php elseif($status === 'expired_token') : ?>

  <section class="component auth-comp center">
    <h1 class="component__heading-1">Password reset link expired</h1>
    <p>Please request a new one and try again</p>
    <a href="<?=AUTH_FORGOT_PASSWORD_PATH?>" class="button">Forgot password</a>
  </section>

<?php elseif($status === 'invalid_token') : ?>

  <section class="component auth-comp center">
    <h1 class="component__heading-1">Invalid reset link</h1>
    <p>Please request a new one and try again</p>
    <a href="<?=AUTH_FORGOT_PASSWORD_PATH?>" class="button">Forgot password</a>
  </section>

<?php else: ?>

  <section class="component auth-comp center">
    <h1 class="component__heading-1">Unknown Error</h1>
    <p>Something went wrong. Please try again later</p>
  </section>

<?php endif; ?>
{{ content-end }}