<?php
/**
 * View Name: verify-account
 * Path: view/auth/verify-account
 * @param array $data arguments passed from controller
 */
?>

{{ title        = "Verify Email Address | <?=APP_NAME?>" }}
{{ body_class   = "auth" }}

{{ content }}
<section class="section auth-comp has-text-centered">
  <div class="container">

    <?php if ($status == 'success') : ?>
      <h1 class="title has-text-success">Congratulations!</h1>
      <p class="subtitle">Your account has been verified successfully.</p>
      <a href="<?=BASE_URL?>login" class="button is-primary">Login to your account</a>

    <?php elseif ($status == 'suspended') : ?>
      <h1 class="title has-text-warning">Account is Disabled</h1>
      <p class="subtitle">Your account is disabled. Please contact the support team for more information.</p>

    <?php elseif ($status == 'invalid_token') : ?>
      <h1 class="title has-text-danger">Invalid Link</h1>
      <p class="subtitle">The verification link is invalid.</p>
      <a href="<?=BASE_URL?>login" class="button is-primary">Go to Login Page</a>

    <?php else : ?>
      <h1 class="title has-text-danger">Error</h1>
      <p class="subtitle">Something went wrong. There was an error verifying your account!</p>
      <a href="<?=BASE_URL?>login" class="button is-primary">Go to Login Page</a>
    <?php endif; ?>

  </div>
</section>
{{ content-end }}