<?php
/**
 * Component Name: cta
 * Path: view/components/cta
 * @param array $args Given arguments on component call
 */
?>

<section class="component cta p-6 has-background-link">
  <div class="container py-6">
    <h2 class="title is-1 has-text-white"><?=$title?></h2>
    <p class="title is-3 has-text-white"><?=$sub_title?></p>
    <p class="has-text-white"><?=$description?></p>
    <a href="<?=$cta_link?>" class="button is-primary is-medium mt-5"><?=$cta_label?></a>
  </div>
</section>