<?php
/**
* Ozz micro framework
* Author: Shakir
* Contact: shakeerwahid@gmail.com
*/

namespace Ozz\Core\system\auth;

class CreateAuth {

  private $migration_dir = __DIR__.SPC_BACK['core_2'].'database/migration/';
  private $controller_dir = __DIR__.SPC_BACK['core_2'].'app/controller/';
  private $model_dir = __DIR__.SPC_BACK['core_2'].'app/model/';
  private $view_dir = __DIR__.SPC_BACK['core_2'].'app/view/';



  public function index($com){
    //Create New Auth
    $this->createAuth();
  }



  /**
   * Create Auth
   */
  public function createAuth(){
    global $utils;
    $errors = [];

    // Users Migration already exist
    $find_user_migration = array_filter(scandir($this->migration_dir), function($item) {
      return $item[0] !== '.' && substr($item, -4) == '.php';
    });

    foreach ($find_user_migration as $k => $v) {
      if(file_exists($this->migration_dir.$v) && is_file($this->migration_dir.$v)){
        if(substr(substr($v, 14), 0, -4) == 'Users'){
          $errors[] = '[Users] migration already exist. Please remove or rename your existing [Users] migration';
        }
      }
    }

    // Users Controller already exist
    if(file_exists($this->controller_dir.'UsersController.php')){
      $errors[] = '[UsersController] already exist. Please remove or rename your existing [UsersController] if it is not generated by auth command.';
    }

    // Users Model already exist
    if(file_exists($this->model_dir.'Users.php')){
      $errors[] = '[Users] Model already exist. Please remove or rename your existing [Users] model class if it is not generated by auth command.';
    }

    // If has any errors
    if(isset($errors) && !empty($errors)){
      ozz_console_error('Can\'t Generate Auth!');
      foreach ($errors as $key => $value) {
        $utils->console_return($value, 'red', '', false, true);
      }
      exit;
    }

    // No errors (Create new auth migration)
    $this->createAuthController('UsersController');
    $this->createAuthModel('Users');
    $this->createAuthMigration('Users');
    $this->runAuthMigration('Users');
  }



  /**
   * Create auth controller
   * @param string Controller Name
   */
  private function createAuthController($name){
    global $utils;
    require 'auth-contents.php';

    $newFile = $this->controller_dir.$name.'.php';
    $controller_file = fopen($newFile, 'w');
    fwrite($controller_file, $auth_controller_content);
    
    $utils->console_return("[$name] generated", 'green');
  }



  /**
   * Create auth model
   * @param string Model Name
   */
  private function createAuthModel($name){
    global $utils;
    require 'auth-contents.php';

    $newFile = $this->model_dir.$name.'.php';
    $model_file = fopen($newFile, 'w');
    fwrite($model_file, $auth_model_content);
    
    $utils->console_return("[$name] model generated", 'green');
  }



  /**
   * Create auth migration file
   * @param string Migration Name
   */
  private function createAuthMigration($name){
    global $utils;
    require 'auth-contents.php';

    $newFile = $this->migration_dir.'mg_'.date('d_m_Y_').$name.'.php';
    $migration_file = fopen($newFile, 'w');
    fwrite($migration_file, $auth_migration_content);
    
    $utils->console_return("[$name] migration file generated", 'green');
  }



  /**
   * Run default auth migration
   * @param string Migration Name
   */
  private function runAuthMigration($name='Users'){
    global $utils;
    if(exec("php ozz migrate $name")){
      $utils->console_return("[$name] table created", 'green');
    }
  }

}
(new CreateAuth)->index($com);