<?php
/**
 * Base layout for Ozz CMS admin
 */

$user = (object) auth_info();
$has_alert = has_error('success') || has_error('error');
$new_entries = $data['notify']['form_entries'];
$new_entries_flag = $new_entries ? '<span class="has-new-notify" title="New entries"></span>' : '';

?>
<!DOCTYPE html>
<html lang="<?=APP_LANG?>">
<head>
  <meta charset=<?=CONFIG['CHARSET']?>>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="csrf-token" content="<?=CSRF_TOKEN?>">
  <link rel="icon" type="image/x-icon" href="<?=ASSETS?>icons/favicon.svg">
  <link rel="stylesheet" href="<?=ASSETS?>css/admin.min.css" nonce="<?=CSP_NONCE?>">
</head>
<body class="ozz-cms {% body_class %}">
  <div class="app-container">

    <!-- Main navigation -->
    <nav class="cms-nav">
      <span class="cms-nav__nav-collapse-trigger"></span>
      <div class="cms-nav__logo">
        <a href="<?=BASE_URL?>" target="_blank">
          <img src="<?=ASSETS?>icons/favicon.svg" alt="Ozz CMS">
        </a>
      </div>

      <ul data-active-link="<?= $context['url_parts'][2] ?? 'dashboard' ?>">
        <li class="dashboard">
          <a href="/admin" class="dashboard">Dashboard</a>
        </li>

        <li class="posts has-child">
          <a href="/admin/posts" class="posts">Posts</a>
          <?= component('submenu', [
            'title' => 'Posts types',
            'slug' => 'posts',
            'items' => $data['post_types'],
            'url_parts' => $context['url_parts']
          ], 'cms/'); ?>
        </li>

        <li class="blocks has-child">
          <a href="/admin/blocks" class="blocks">Blocks</a>
          <?= component('submenu', [
            'title' => 'Blocks',
            'slug' => 'blocks',
            'items' => $data['blocks'],
            'url_parts' => $context['url_parts']
          ], 'cms/'); ?>
        </li>

        <li class="taxonomy has-child">
          <a href="/admin/taxonomy" class="taxonomy">Taxonomy</a>
          <?= component('submenu', [
            'title' => 'Taxonomy',
            'slug' => 'taxonomy',
            'items' => $data['taxonomies'],
            'url_parts' => $context['url_parts']
          ], 'cms/'); ?>
        </li>

        <li class="forms has-child">
          <a href="/admin/forms" class="forms">Forms & Entries <?=$new_entries_flag?></a>
          <?= component('submenu', [
            'title' => 'Forms & Entries',
            'slug' => 'forms',
            'items' => $data['forms'],
            'new_items' => $new_entries,
            'url_parts' => $context['url_parts']
          ], 'cms/'); ?>
        </li>

        <li class="media">
          <a href="/admin/media" class="media">Media</a>
        </li>

        <li class="settings">
          <a href="/admin/settings" class="settings">Settings</a>
        </li>
      </ul>
    </nav>

    <main>
      <header class="cms-header">
        <div class="cms-header__container">
          <div class="cms-header__left-content">
            <div class="cms-global-search">
              <div class="ozz-fm__field search-wrapper">
                <input type="search" name="cms-global-search-field" placeholder="Search...">
              </div>
              <div class="cms-global-search__result-wrapper">
                <div class="cms-global-search__result"></div>
              </div>
            </div>
          </div>

          <div class="cms-header__right-content">
            <!-- Specific action injection -->
            <div class="cms-header__action-injection"></div>

            <!-- Language switcher -->
            <div class="cms-header__language-switch">
              <span class="current-lang"><?=APP_LANG?></span>
              <ul class="dropdown">
                <?php foreach ($data['languages'] as $code => $language) : ?>
                  <li><a href="/lang/<?=$code?>"><?=$language?></a></li>
                <?php endforeach; ?>
              </ul>
            </div>

            <!-- User information (dropdown) -->
            <div class="cms-header__user-info">
              <div class="cms-header__avatar">
                <img src="<?=get_gravatar($user->email, 80);?>" alt="Avatar">
                <span class="cms-header__avatar-arrow"></span>
              </div>
              <div class="cms-header__info">
                <div class="user-info">
                  <img src="<?=get_gravatar($user->email, 80);?>" alt="Avatar">
                  <p>
                    <strong><?=$user->first_name.' '.$user->last_name?></strong><br>
                    <?=$user->email?><br>
                    <span class="light-text">@<?=$user->username?></span>
                  </p>
                </div>
                <p class="mode-switcher">
                  <label for="ozz-color-theme-switcher">Dark Mode</label>
                  <input type="checkbox" class="switch" id="ozz-color-theme-switcher">
                </p>
                <a href="<?=AUTH_PATHS['logout']?>" class="button small danger">Logout</a>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div class="common-alert-bar">
        <?=$has_alert ? show_errors(null, false) : ''?>
      </div>

    {% content %}

    <?php include __DIR__.'/../partials/block-editor-hidden-dom.php'; ?>

    <div class="ozz-cms-popup">
      <div class="container">
        <div class="ozz-cms-popup__box">
          <span id="cms-popup-close"></span>
          <div id="cms-popup-content"></div>
        </div>
      </div>
    </div>
    </main>
  </div>
<script nonce="<?=CSP_NONCE?>">
  const DATA = JSON.parse('<?=json_encode([
    'HOST'     => $context['request']['host'],
    'URL'      => $context['url'],
    'SEGMENTS' => $context['url_parts'],
    'CMS_URL'  => '/'.$context['url_parts'][1].'/'
  ]);
  ?>');
</script>
<script nonce="<?=CSP_NONCE?>" src="<?=ASSETS?>js/admin.min.js"></script>
</body>
</html>