<!DOCTYPE html>
<html lang="<?=APP_LANG?>">
<head>
  <meta charset=<?=CONFIG['CHARSET']?>>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="keywords" content="{% keywords %}">
  <meta name="description" content="{% description %}">
  <meta name="robots" content="index, follow">
  <meta name="csrf-token" content="<?=CSRF_TOKEN?>">
  <meta name="url" content="<?=BASE_URL?>">
  <link rel="icon" type="image/x-icon" href="<?=ASSETS?>icons/favicon.svg">
  <link rel="stylesheet" href="<?=ASSETS?>admin/css/admin.css" nonce="<?=CSP_NONCE?>">
</head>
<body class="ozz-cms {% body_class %}">
  <div class="app-container">
    <nav class="cms-nav">
      <ul data-active-link="<?= $context['url_parts'][2] ?? 'dashboard' ?>">
        <li class="dashboard">
          <a href="/admin" class="dashboard">Dashboard</a>
        </li>
        <li class="posts has-child">
          <a href="/admin/posts" class="posts">Posts</a>
          <ul>
            <li><a href="/admin/posts">All</a></li>
            <?php foreach ($data['post_types'] as $key => $value) : ?>
              <li><a href="/admin/posts/<?=$key?>"><?=ucfirst($value['label'])?></a></li>
            <?php endforeach; ?>
          </ul>
        </li>
        <li class="blocks">
          <a href="/admin/blocks" class="blocks">Blocks</a>
        </li>
        <li class="terms">
          <a href="/admin/terms" class="terms">Terms</a>
        </li>
        <li class="settings">
          <a href="/admin/settings" class="settings">Settings</a>
        </li>
      </ul>
      <div class="cms-nav__bottom">
        <span class="nav-collapse-trigger"></span>
      </div>
    </nav>

    <main>
      <header class="cms-header">
        <div class="cms-header__container">
          <div class="cms-header__language-switch align-right">
            <span class="current-lang"><?=$data['languages'][APP_LANG]?></span>
            <ul class="dropdown">
              <?php foreach ($data['languages'] as $code => $language) : ?>
                <li><a href="/lang/<?=$code?>"><?=$language?></a></li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      </header>
    {% content %}
    </main>
  </div>
<script nonce="<?=CSP_NONCE?>" src="<?=ASSETS?>admin/js/admin.js"></script>
</body>
</html>