<?php
/**
 * Base layout for Ozz CMS admin
 */

use Ozz\Core\Auth;
$user = (object) Auth::info();

?>
<!DOCTYPE html>
<html lang="<?=APP_LANG?>">
<head>
  <meta charset=<?=CONFIG['CHARSET']?>>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% title %}</title>
  <meta name="csrf-token" content="<?=CSRF_TOKEN?>">
  <link rel="icon" type="image/x-icon" href="<?=ASSETS?>icons/favicon.svg">
  <link rel="stylesheet" href="<?=ASSETS?>admin/css/admin.css" nonce="<?=CSP_NONCE?>">
</head>
<body class="ozz-cms {% body_class %}">
  <div class="app-container">

    <!-- Main navigation -->
    <nav class="cms-nav">
      <div class="cms-nav__logo">
        <img src="<?=ASSETS?>icons/favicon.svg" alt="Ozz CMS">
      </div>
      <ul data-active-link="<?= $context['url_parts'][2] ?? 'dashboard' ?>">
        <li class="dashboard">
          <a href="/admin" class="dashboard">Dashboard</a>
        </li>
        <li class="posts has-child">
          <a href="/admin/posts" class="posts">Posts</a>
          <ul>
            <label>
              <span>Post types</span>
              <a href="/admin/posts"><span class="button mini">All</span></a>
            </label>
              <?php
                foreach ($data['post_types'] as $key => $value) :
                  $active_cls = (isset($context['url_parts'][3]) && $context['url_parts'][3] == $key) ? 'active' : '';
              ?>
                <li class="<?=$active_cls?>">
                  <a href="/admin/posts/<?=$key?>"><?=ucfirst($value['label'])?></a>
                </li>
              <?php endforeach; ?>
          </ul>
        </li>
        <li class="blocks">
          <a href="/admin/blocks" class="blocks">Blocks</a>
        </li>
        <li class="terms">
          <a href="/admin/terms" class="terms">Terms</a>
        </li>
        <li class="media">
          <a href="/admin/media" class="media">Media</a>
        </li>
        <li class="settings">
          <a href="/admin/settings" class="settings">Settings</a>
        </li>
      </ul>
      <div class="cms-nav__bottom">
        <span class="nav-collapse-trigger"></span>
      </div>
    </nav>

    <main>
      <header class="cms-header">
        <div class="cms-header__container">
          <div class="cms-header__left-content">
            <!-- empty -->
          </div>

          <div class="cms-header__right-content">
            <!-- Specific action injection -->
            <div class="cms-header__action-injection"></div>

            <!-- Language switcher -->
            <div class="cms-header__language-switch">
              <span class="current-lang"><?=APP_LANG?></span>
              <ul class="dropdown">
                <?php foreach ($data['languages'] as $code => $language) : ?>
                  <li><a href="/lang/<?=$code?>"><?=$language?></a></li>
                <?php endforeach; ?>
              </ul>
            </div>

            <!-- User information (dropdown) -->
            <div class="cms-header__user-info">
              <div class="cms-header__avatar">
                <img src="<?=get_gravatar($user->email, 80);?>" alt="Avatar">
                <span class="cms-header__avatar-arrow"></span>
              </div>
              <div class="cms-header__info">
                <p>
                  <strong><?=$user->first_name.' '.$user->last_name?></strong><br>
                  <span class="light-text">@<?=$user->username?></span>
                </p>
                <p><?=$user->email?></p>
                <p>Dark Mode <input type="checkbox" class="ozz-color-theme-switcher switch"></p>
                <a href="<?=AUTH_PATHS['logout']?>" class="button small danger">Logout</a>
              </div>
            </div>
          </div>
        </div>
      </header>

      <div class="common-alert-bar">
        <?=has_error('success') || has_error('error') ? show_errors(null, false) : ''?>
      </div>

    {% content %}

    <?php include __DIR__.'/../partials/block-editor-hidden-dom.php'; ?>

    <div class="ozz-cms-popup">
      <div class="container">
        <div class="ozz-cms-popup__box">
          <span id="cms-popup-close"></span>
          <div id="cms-popup-content"></div>
        </div>
      </div>
    </div>
    </main>
  </div>
<script nonce="<?=CSP_NONCE?>" src="<?=ASSETS?>admin/js/vendor/sortable.min.js"></script>
<script nonce="<?=CSP_NONCE?>" src="<?=ASSETS?>js/ozz.js"></script>
<script nonce="<?=CSP_NONCE?>" src="<?=ASSETS?>admin/js/admin.js"></script>
</body>
</html>